version: '3.7'
services:
  db:
    image: "postgres:11"
    container_name: "postgres_database"
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: